# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 00:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visivel', models.CharField(choices=[('PR', 'Privada'), ('PB', 'Pública')], default='PR', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Agenda_Institucional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Compromisso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('descricao', models.TextField()),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_agenda_compromissos', to='agenda.Agenda')),
                ('institucinal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_institucional_compromissos', to='agenda.Agenda_Institucional')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=128)),
                ('datanascimento', models.DateField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='agenda',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.Usuario'),
        ),
    ]
